### PR TITLE
Add italian translation

### PR DESCRIPTION
**Pull request by SimoneN64**
May need some reviewing. I can notice, and I can't figure out why, that "Press new button" isn't actually getting translated, it stays in english.

### CODE REVIEW

**Comment by skylersaleh** [comment]
Hey Simone, 

I found a couple of areas where the translation overlaps the UI. Can you please fix them? 

image

The "+New" button is showing up translated for me. Are you referring to a different button? 
image

Thanks!

**Comment by SimoneN64** [comment]
Hey, I'll have to be clever and come up with semantically/grammatically correct but also short italian sentences to fix those :D And no, I'm referring to the text that shows up when you rebind in the settings. The original string is "Press new button"

**Comment by skylersaleh** [comment]
Oh I see, I just pushed a change to dev that should fix that.

**Comment by SimoneN64** [comment]
I can confirm that text now gets translated correctly

**Pull request merged**
