### PR TITLE
[Frontend] Do not teleport the user to the home dir on folder open error

### PR DESCRIPTION
**Pull request by kylon**
this is counter-intuitive and super annoying, it now shows nothing, same as file managers when cannot open a folder (maybe a message can be shown in ui, but out of this pr scope)

this way you can just go back to parent folder instead of walking full path again

### CODE REVIEW

**Comment by skylersaleh** [comment]
This behavior was specifically put in to avoid becoming non-navigateable when getting navigating to a directory that has its entire upwards tree non-navigatable (this can happen when you navigate to the parent directory of your users home directory which in a lot of distros is not readable by non-superuser processes (to avoid programs getting all the usernames)).

**Comment by kylon** [comment]
i see, still, imo, this behaviour is not a valid fix/workaround for that case
we can add a "home" button to go to home instead of doing that, i think this is the correct way to handle this

**Comment by skylersaleh** [comment]
Adding a button could be an okay compromise. Could you add that to your PR?

**Comment by kylon** [comment]
done

**Comment by skylersaleh** [comment]
Thank you 👍🏽

**Pull request merged**
