### PR TITLE
Added Russian Localization

### PR DESCRIPTION
**Pull request by GreatA1exander**
Told you I'd give it a go! Fun stuff :)

### CODE REVIEW

**Comment by skylersaleh** [comment]
The only issue I see is this section cuts off. 

image

Maybe remove the space between the number and "bit" and change +/- to ±

**Comment by GreatA1exander** [comment]
Changed that over, looked fine on my compilation.
Screenshot 2023-08-03 at 1 08 12 PM

**Comment by skylersaleh** [comment]
Looks good to me! Are you ready for me to merge?

**Comment by GreatA1exander** [comment]
Yup!

**Pull request merged**
